#pragma once
#include <glad/glad.h>

//VBO usage types
#define STATIC_USAGE GL_STATIC_DRAW
#define STREAM_USAGE GL_STREAM_DRAW
#define DYNAMIC_USAGE GL_DYNAMIC_DRAW

//datatypes
#define FLOAT GL_FLOAT

//values
#define FALSE GL_FALSE
#define TRUE GL_TRUE

//texture
#define TEXTURE_WRAP_CLAMP_TO_EDGE GL_CLAMP_TO_EDGE
#define TEXTURE_WRAP_REPEAT GL_REPEAT
#define TEXTURE_WRAP_MIRROR GL_MIRRORED_REPEAT
#define TEXTURE_FILTER_LINEAR GL_LINEAR
#define TEXTURE_FILTER_NEAREST GL_NEAREST
#define COLOR_CHANNEL_RGB GL_RGB
#define COLOR_CHANNEL_RGBA GL_RGBA

//primitives
#define TRIANGLES GL_TRIANGLES
